# Generated by Django 6.0.1 on 2026-01-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyManagementGeneralInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('faculty_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('personal_email', models.CharField(blank=True, max_length=225, null=True)),
                ('college_email', models.CharField(blank=True, max_length=225, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faculty_management_general_information',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='faculty',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Vice Principal', 'Vice Principal'), ('Advisor', 'Advisor'), ('Mentor', 'Mentor'), ('Teacher', 'Teacher')], max_length=50),
        ),
    ]
